function output = assign_marker_to_landmark(landmark, label)
%% Create landmarks
% Expects the file names to include both the bone and the position, e.g.,
% tibia-medial or femur_proximal. Doesn't care about order or what
% separates the words.
%
% If neither can be found, it looks for the first letter of each word,
% e.g., for tibia medial it looks for TM.
% 
% For Patella, it needs either distal or both inferior and superior.
%% Tibia
output.tibia.medial = landmark ...
    .contains({'tibia', 'medial'})...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.probe)));
output.tibia.lateral = landmark ...
    .contains({'tibia', 'lateral'})...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.probe)));
output.tibia.distal = landmark ...
    .contains({'tibia', 'distal'})...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.probe)));

output.tibia.tracker = Option(landmark(1)) ...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.tibia)));

%% Femur
output.femur.medial = landmark ...
    .contains({'femur', 'medial'})...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.probe)));
output.femur.lateral = landmark ...
    .contains({'femur', 'lateral'})...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.probe)));
output.femur.proximal = landmark ...
    .contains({'femur', 'proximal'})...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.probe)));

output.femur.tracker = Option(landmark(1)).and_then(@(x) x.probes.and_then(@(c) c.with_label(label.femur)));

% output.femur.tracker = landmark(1).probes.with_label(label.femur);
%% Patella
output.patella.medial = landmark ...
    .contains({'patella', 'medial'})...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.probe)));
output.patella.lateral = landmark ...
    .contains({'patella', 'lateral'})...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.probe)));
output.patella.distal = landmark ...
    .contains({'patella', 'distal'})...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.probe)));
output.patella.inferior = landmark ...
    .contains({'patella', 'inferior'})...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.probe)));
output.patella.superior = landmark ...
    .contains({'patella', 'superior'})...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.probe)));
output.patella.tracker = Option(landmark(1)) ...
    .and_then(@(x) x.probes.and_then(@(c) c.with_label(label.patella)));
end
