function landmarks = create_rigid_bodies(landmark_raw_data, label)
landmarks.tibia.medial = extract_from_label( ...
    landmark_raw_data(find_landmark(landmark_raw_data, {'tibia', 'medial'})).probes, ...
    label.probe);
landmarks.tibia.lateral = extract_from_label( ...
    landmark_raw_data(find_landmark(landmark_raw_data, {'tibia', 'lateral'})).probes, ...
    label.probe);
landmarks.tibia.distal = extract_from_label( ...
    landmark_raw_data(find_landmark(landmark_raw_data, {'tibia', 'distal'})).probes, ...
    label.probe);
landmarks.tibia.tracker = extract_from_label( ...
    landmark_raw_data(1).probes, ...
    label.tibia...
    );

landmarks.femur.medial = extract_from_label( ...
    landmark_raw_data(find_landmark(landmark_raw_data, {'femur', 'medial'})).probes, ...
    label.probe);
landmarks.femur.lateral = extract_from_label( ...
    landmark_raw_data(find_landmark(landmark_raw_data, {'femur', 'lateral'})).probes, ...
    label.probe);
landmarks.femur.proximal = extract_from_label( ...
    landmark_raw_data(find_landmark(landmark_raw_data, {'femur', 'proximal'})).probes, ...
    label.probe);
landmarks.femur.tracker = extract_from_label( ...
    landmark_raw_data(1).probes, ...
    label.tibia...
    );
end
